### ISSUE TITLE
Random Item Placement?

### ISSUE THREAD

**Issue by Uncle-Pyro** [Al-Asl/AutoLevel#2]
I would like to place items(like chests) in random places in the rooms, within guidelines like always along a wall and never in a doorway. Is there a way to do this with this asset?

**Comment by Al-Asl** [comment]
in the repo you can nest anything under a block asset and export it with the rest of the level, so you can use the edge_a block and nest the chest under it, you can nest whatever you want scripts, lights, particle system .. etc, AutoLevel doesn't preview these changes but it can export them hitting the 'export objects' button from the level builder or the level builder menu. To have random chests you can do that with a little trick by having two versions of the edge_a block one of which have the chest nested under it, then you can control its weight individually, if you have any other questions please join me on [server](https://discord.gg/7DWZAQUh).
